### ISSUE TITLE
如何调用采集机器的脚本？

### ISSUE THREAD

**Issue by JunJun-Love-Amber** [Cryin/AssetsView#1]
如何调用采集机器的脚本？我在控制器没有发现采集的代码？

**Comment by Cryin** [comment]
网络拓扑发现目前已经基本开发测试完成，但还未添加到AssetsView项目中。已经在todo list中了，不过由于最近工作繁忙，可能会晚些时间完成、提交。单独的网络资产拓扑发现模块可查看项目地址：https://github.com/hardyguo/visualization_asset_sms
