### ISSUE TITLE
搭建php的时候出现了问题

### ISSUE THREAD

**Issue by libqn** [Cryin/AssetsView#2]
你好，很感谢您提供这个项目，以供学习。但是我在部署的过程中遇到了一些问题，我将文件下载下来，然后用的集成环境xampp，将文件放到htdocs中，数据库密码也改成root，并创建了assets_scan的数据库，并导入了数据，但是我访问首页的时候，跳转到AssetsView/Dashboard/loginpage页面，弹出object not found，404这个错误，请问是我哪里没有配置对吗？还是环境缺少什么东西？

**Comment by Cryin** [comment]
检查下rewrite规则路径和config中的路径设置是不是和当前程序所在路径一致，因为看不到具体信息，我也不好确定。如果有疑问可以联系qq交流。

**Comment by libqn** [comment]
@Cryin 您好，我的qq是704013281，我没有找到你的qq号信息。麻烦您了

**Comment by libqn** [comment]
找到问题的原因了，是我没有将.htaccess拷贝到网站目录当中，作者也加我的QQ了，十分感谢。
